### ISSUE TITLE
installing nodejs dependencies

### ISSUE THREAD

**Issue by empierre** [ehartsuyker/node-deb#9]
Hello,

  there is no npm install of dependencies upon startup, could you add this too ?

**Comment by ehartsuyker** [comment]
@empierre Slow response because this has been mostly stable and working for the people I wrote this for. Anywho.

I'm marking this as won't fix because I think it is better to do your `npm install` before packing and include the libs in your `.deb`. If this isn't what you can do, you can change the start command to do an `rm -rf && npm install && node app.js` if you want. Or probably the best would be to override the `postinst` template to do this when the package is installed.

**Comment by ehartsuyker** [comment]
@empierre I'm actually reopening this and will fix it soon as we ran into a problem of compiling something on system A, packaging, then installing it on system B didn't work.

**Comment by empierre** [comment]
that is good news for npm install on 0.10 nodejs (+nmp) version has issues...
